# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [124]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [125]:
# your code here
print(np.version)
print('My NumPy version is %s.' %np.version.version)

<module 'numpy.version' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>
My NumPy version is 1.16.5.


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [126]:
# Method 1
a = np.random.random((2, 3, 5))
print(a)

[[[0.22735809 0.50564077 0.13661361 0.5626026  0.68413503]
  [0.46302315 0.89455322 0.63396838 0.07094991 0.30230736]
  [0.03263088 0.38167449 0.88649366 0.20478791 0.90936338]]

 [[0.30283531 0.79724885 0.27583074 0.51885704 0.62010037]
  [0.5061462  0.4387654  0.13446223 0.12407845 0.12106477]
  [0.1392939  0.56056093 0.04831316 0.76687046 0.07381112]]]


In [127]:
# Method 2
import random
a1 = np.array(random.sample(range(0,101),30)).reshape(2,3,5)
print(a1)

[[[25  9 59 23 68]
  [99 79 84 26 17]
  [95 60 45 35 38]]

 [[20 53 88 27  8]
  [31 64 62 90 43]
  [ 1 39 30 63 78]]]


In [128]:
# Method 3
a2 = np.arange(0,90,3).reshape(2, 3, 5)
print(a2)

[[[ 0  3  6  9 12]
  [15 18 21 24 27]
  [30 33 36 39 42]]

 [[45 48 51 54 57]
  [60 63 66 69 72]
  [75 78 81 84 87]]]


In [129]:
a3 = np.array([np.random.randint(0,100,1)[0] for i in range(30)]).reshape(2, 3, 5)
print(a3)

[[[26 34 16 96 10]
  [26 13 70 39 84]
  [84 21 59 51 68]]

 [[15 42 46  7 19]
  [ 1 96 60 23 30]
  [59 99 69 22 16]]]


#### 4. Print *a*.


In [130]:
# your code here
print(a)

[[[0.22735809 0.50564077 0.13661361 0.5626026  0.68413503]
  [0.46302315 0.89455322 0.63396838 0.07094991 0.30230736]
  [0.03263088 0.38167449 0.88649366 0.20478791 0.90936338]]

 [[0.30283531 0.79724885 0.27583074 0.51885704 0.62010037]
  [0.5061462  0.4387654  0.13446223 0.12407845 0.12106477]
  [0.1392939  0.56056093 0.04831316 0.76687046 0.07381112]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [131]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [132]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [133]:
# your code here
print('a and b have the same size.' if a.size == b.size else 'a and b have different sizes.')

a and b have the same size.


#### 8. Are you able to add *a* and *b*? Why or why not?


In [134]:
# your answer here
try:
    np.add(a,b)
    
except ValueError:
    print('Shape of Matrix a differs from which of Matrix b.\nOperands could not be broadcast together with shapes (2,3,5) (5,2,3)')

Shape of Matrix a differs from which of Matrix b.
Operands could not be broadcast together with shapes (2,3,5) (5,2,3)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [135]:
# your code here
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [136]:
# your code/answer here
d = np.add(a, c)
print(d,'\nArrays sharing the same structure can be combined with addition.' if type(np.add(a,c)) == np.ndarray else 'Addition cannot be processed.' )

[[[1.22735809 1.50564077 1.13661361 1.5626026  1.68413503]
  [1.46302315 1.89455322 1.63396838 1.07094991 1.30230736]
  [1.03263088 1.38167449 1.88649366 1.20478791 1.90936338]]

 [[1.30283531 1.79724885 1.27583074 1.51885704 1.62010037]
  [1.5061462  1.4387654  1.13446223 1.12407845 1.12106477]
  [1.1392939  1.56056093 1.04831316 1.76687046 1.07381112]]] 
Arrays sharing the same structure can be combined with addition.


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [137]:
# your code/answer here
print('Array a:\n', a,'\n\nArray d:\n', d)
#The difference of all elements, which share the same index in Array a and Array c, is one.
#This is because Array c was created by reshaping Array b, which its elements are all 'ones' upon creation.

Array a:
 [[[0.22735809 0.50564077 0.13661361 0.5626026  0.68413503]
  [0.46302315 0.89455322 0.63396838 0.07094991 0.30230736]
  [0.03263088 0.38167449 0.88649366 0.20478791 0.90936338]]

 [[0.30283531 0.79724885 0.27583074 0.51885704 0.62010037]
  [0.5061462  0.4387654  0.13446223 0.12407845 0.12106477]
  [0.1392939  0.56056093 0.04831316 0.76687046 0.07381112]]] 

Array d:
 [[[1.22735809 1.50564077 1.13661361 1.5626026  1.68413503]
  [1.46302315 1.89455322 1.63396838 1.07094991 1.30230736]
  [1.03263088 1.38167449 1.88649366 1.20478791 1.90936338]]

 [[1.30283531 1.79724885 1.27583074 1.51885704 1.62010037]
  [1.5061462  1.4387654  1.13446223 1.12407845 1.12106477]
  [1.1392939  1.56056093 1.04831316 1.76687046 1.07381112]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [138]:
# your code here
e = np.multiply(a, c)
print(e)

[[[0.22735809 0.50564077 0.13661361 0.5626026  0.68413503]
  [0.46302315 0.89455322 0.63396838 0.07094991 0.30230736]
  [0.03263088 0.38167449 0.88649366 0.20478791 0.90936338]]

 [[0.30283531 0.79724885 0.27583074 0.51885704 0.62010037]
  [0.5061462  0.4387654  0.13446223 0.12407845 0.12106477]
  [0.1392939  0.56056093 0.04831316 0.76687046 0.07381112]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [139]:
# your code/answer here
print('Array e equals to a.' if e.all() == a.all() else 'Array e does not equal to a.')
#Array c is of all ones. Multiplying each element in Array a with one generates the same element in Array e. 

Array e equals to a.


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [154]:
# your code here
d_max = np.amax(d)
d_min = np.min(d)
d_mean = np.mean(d)
print('Maximum value in Array d is %f.\nMinimum value in Array d is %f.\nMean of Array d is %f.' %(d_max, d_min, d_mean))

Maximum value in Array d is 1.909363.
Minimum value in Array d is 1.032631.
Mean of Array d is 1.410811.


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [249]:
# your code here
f = np.empty((2, 3, 5))
print(f)

[[[ 25.  75.  25.  75.  75.]
  [ 75.  75.  75.  25.  25.]
  [  0.  25.  75.  25. 100.]]

 [[ 25.  75.  25.  75.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 25.  75.  25.  75.  25.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [257]:
# fix later to see if below would work
# # your code here
# # f = [25 for val in d if d_mean > val > d_min else(75 for val in d if d_max > val > d_mean else (50 for val in d if val == d_mean else ( 0 for val in d if val == d_min else (100 for val in d if val == d_max)))

# for val in d:
#     if d_mean > val and  val > d_min:
#         f.append(25)
#         if (d_max > val > d_mean):
#             f.append(75)
#             if val == d_mean:
#                 f.append(50)
#                 if val == d_min:
#                     f.append(0)
#                 elif val == d_max:
#                     f.append(100)
# # f = np.where(f)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [259]:
# your code here
f = np.empty((2,3,5))

for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range(len(d[x,y])):
            if d[x,y,z] < d_mean and d[x,y,z] > d_min:
                f[x,y,z] = 25
            elif d[x,y,z] < d_max and d[x,y,z] > d_mean:
                f[x,y,z] = 75
            elif d[x,y,z] == d_mean:
                f[x,y,z] = 50
            elif d[x,y,z] == d_min:
                f[x,y,z] == 0
            elif d[x,y,z] == d_max:
                f[x,y,z] = 100
                                
print('Array d:\n', d,'\n\n\nArray f: \n', f)   

Array d:
 [[[1.22735809 1.50564077 1.13661361 1.5626026  1.68413503]
  [1.46302315 1.89455322 1.63396838 1.07094991 1.30230736]
  [1.03263088 1.38167449 1.88649366 1.20478791 1.90936338]]

 [[1.30283531 1.79724885 1.27583074 1.51885704 1.62010037]
  [1.5061462  1.4387654  1.13446223 1.12407845 1.12106477]
  [1.1392939  1.56056093 1.04831316 1.76687046 1.07381112]]] 


Array f: 
 [[[ 25.  75.  25.  75.  75.]
  [ 75.  75.  75.  25.  25.]
  [  0.  25.  75.  25. 100.]]

 [[ 25.  75.  25.  75.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 25.  75.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [255]:
f_letter = np.empty((2,3,5),dtype=str)
f_letter

for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range(len(d[x,y])):
            if d[x,y,z] < d_mean and d[x,y,z] > d_min:
                f_letter[x,y,z] = 'B'
            elif d[x,y,z] < d_max and d[x,y,z] > d_mean:
                f_letter[x,y,z] = 'D'
            elif d[x,y,z] == d_mean:
                f_letter[x,y,z] = 'C'
            elif d[x,y,z] == d_min:
                f_letter[x,y,z] = 'A'
            elif d[x,y,z] == d_max:
                f_letter[x,y,z] = 'E'
print(f_letter)

[[['B' 'D' 'B' 'D' 'D']
  ['D' 'D' 'D' 'B' 'B']
  ['A' 'B' 'D' 'B' 'E']]

 [['B' 'D' 'B' 'D' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['B' 'D' 'B' 'D' 'B']]]
